name: assignment_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.2
  firebase_storage: ^11.7.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/istockphoto-1295633127-1024x1024.jpg
